---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    db_user: vagrant
    db_pass: vagrant
    db_name: vagrant
    db_dump: /db/db.sql
    site_url: vagrant-ansible.local
  pre_tasks:
  - name: update apt cache
    apt: update_cache=yes
  tasks:
  - name: install desired packages
    apt: name={{ item }} state=present
    with_items:
    #Things I like to have
    - vim
    - htop
    - lynx
    - curl
    - zsh
    - zip
  roles:
  - webserver
  - database
  - package-management