---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    db_user: vagrant
    db_pass: vagrant
    db_name: vagrant
    db_dump: /db/db.sql
    site_url: vagrant-ansible.local
  pre_tasks:
  - include: tasks/pre_tasks.yml
  - name: update apt cache
    apt: update_cache=yes
  roles:
  - webserver
  - database
  - package-management
  tasks:
  - name: install desired packages
    apt: name={{ item }} state=present
    with_items:
    #Things I like to have
    - vim
    - htop
    - lynx
    - curl
    - zsh
    - zip
  - include: tasks/post_tasks.yml
