---
- name: install mysql
  apt: name={{ item }} state=present
  with_items:
  - mysql-server-5.6
  - mysql-client-5.6
  - python-mysqldb
- name: create database
  mysql_db:
    name={{ db_name }}
    state=present
- name: import database
  mysql_db:
    name={{ db_name }}
    state=import
    target={{ db_dump }}
- name: create database user
  mysql_user:
    name={{ db_user }}
    password={{ db_pass }}
    priv={{ db_name }}.*:ALL,GRANT
    state=present
